services:
  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  frontend:
    name: frontend
  backend:
    name: backend