services:
  web:
    depends_on:
      - redis
    build:
      context: .
      network: host
    image: tyi/webapp
    container_name: web
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "curl", "localhost:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  frontend:
    name: frontend
  backend:
    name: backend
volumes:
  redis_data:
    name: redis_data